# Taken from https://cibuildwheel.readthedocs.io/en/stable/setup/

name: Wheels build

on: [pull_request, workflow_dispatch]

jobs:
    build_wheels_and_sdist:
        name: Build wheels and sdist on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.9'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -r requirements_dev.txt
                  pip install build

            - name: Build wheels and sdist
              run: python -m build

            - name: Upload wheels
              uses: actions/upload-artifact@v4
              with:
                  name: wheel-${{ matrix.os }}-${{ matrix.python-version }}
                  path: wheels/*.whl

            - name: Upload sdist
              uses: actions/upload-artifact@v4
              with:
                  name: sdist-${{ matrix.os }}-${{ matrix.python-version }}
                  path: dist/*.tar.gz
